baseURL = 'http://mjmorse.com/'
locale = 'en-us'
title = 'Matt Morse'
theme = "shibui"
summaryLength = 15
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = true
  tabWidth = 4
  style = "algol_nu"

[params]
  [params.author]
    name = "Matt Morse"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 2 
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3 

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/matthewjmorse/"
    weight = 1
  [[menu.footer]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=wtaBtd8AAAAJ&hl=en&oi=ao"
    weight = 2
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/mmorse1217"
    weight = 3
